const MODELS_OBJECT = {
  kina: {
    id: 1,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "kina",
    model: "kina.glb",
    video: "Kina.mp4",
    date: "Jul 06, 2023 07:10:00",
    color: "green",
  },
  haochen: {
    id: 2,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "haochen",
    model: "haochen.glb",
    video: "Haochen.mp4",
    date: "Jul 05, 2023 19:00:00",
    color: "white",
  },
  cheryl: {
    id: 3,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "cheryl",
    model: "cheryl.glb",
    video: "Cheryl.mp4",
    date: "Jul 05, 2023 07:07:07",
    color: "green",
  },
  shirley: {
    id: 4,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "shirley",
    model: "shirley.glb",
    video: "Shirley.mp4",
    date: "Jul 03, 2023 14:17:03",
    color: "green",
  },
  liki: {
    id: 5,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "liki",
    model: "liki.glb",
    video: "Liki.mp4",
    date: "Jul 04, 2023 20:00:00",
    color: "green",
  },
  cash: {
    id: 6,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "cash",
    model: "cash.glb",
    video: "Cash.mp4",
    date: "Jul 02, 2023 07:06:59",
    color: "white",
  },
  yan: {
    id: 7,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "yan",
    model: "yan.glb",
    video: "Yan.mp4",
    date: "Jul 03, 2022 10:03:00",
    color: "green",
  },
  isabella: {
    id: 8,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    name: "isabella",
    model: "isabella.glb",
    video: "Isabella.mp4",
    date: "Jul 06, 2023 00:01:00",
    color: "blue",
  },
};

export default MODELS_OBJECT;
